import asyncio
import aiohttp

# Define the bot token and chat ID
bot_token = "7389558566:AAFHcups9MxcN2FriTzCO-fAotxXZO7oh48"
chat_id = "5267098233"

# Define the messages to be sent
messages = [
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
    "you idiot",
   
]

# Asynchronous function to send a message using the Telegram Bot API
async def send_message(session, token, chat_id, text):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": text
    }
    async with session.post(url, data=payload) as response:
        if response.status == 200:
            print(f"Message sent successfully: {text}")
        else:
            print(f"Failed to send message: {text}, status code: {response.status}")

# Main asynchronous function to send all messages
async def send_all_messages():
    async with aiohttp.ClientSession() as session:
        tasks = [send_message(session, bot_token, chat_id, message) for message in messages]
        await asyncio.gather(*tasks)

# Run the main function
asyncio.run(send_all_messages())
